apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ service.name }}-scaler
  namespace: zgw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ service.name }}
  minReplicas: {{ scaler.min_replicas }}
  maxReplicas: {{ scaler.max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
