---

apiVersion: v1
kind: Service
metadata:
  name: postgres
# See https://coderjourney.com/using-kubernetes-persistent-volumes/

spec:
  ports:
    - port: 5432
  selector:
    app: postgres

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgre
          name: postgres
          env:
            - name: POSTGRES_USER
              value: zrc
            - name: POSTGRES_PASSWORD
              value: zrc
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
